/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HttpHeadersGrid: typeof import('./components/HttpHeadersGrid.vue')['default']
    ProbeCell: typeof import('./components/ProbeCell.vue')['default']
    ProviderCell: typeof import('./components/ProviderCell.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./components/TopBar.vue')['default']
    UiConfirmDialog: typeof import('./components/UiConfirmDialog.vue')['default']
    UiSnackbar: typeof import('./components/UiSnackbar.vue')['default']
    WorldMap: typeof import('./components/WorldMap.vue')['default']
  }
}
